### ISSUE TITLE
An error when running train_short_term.py

### ISSUE THREAD

**Issue by FrazierLei** [facebookresearch/QuaterNet#1]
When running train_short_term.py, it raised an error.
> xxx@amax:~/code/QuaterNet-master$ python train_short_term.py
>   parameters: 9526128
>Training on 360 sequences, validating on 0 sequences.
>Training for 3000 epochs
>Traceback (most recent call last):
>  File "train_short_term.py", line 32, in <module>
>    model.train(dataset, target_length, sequences_train, sequences_valid, batch_size=60, >n_epochs=3000)
>  File "/home/xxx/code/QuaterNet-master/common/pose_network.py", line 133, in train
>    gradient_norms.append(nn.utils.clip_grad_norm_(self.model.parameters(), gradient_clip).item())
>AttributeError: 'float' object has no attribute 'item'

I don't know much about PyTorch, is it caused by the version of those libs?
I'm using Ubuntu16.04, python3.5.4 and torch0.4.1.post2.

**Comment by dariopavllo** [comment]
This issue has been introduced by a slight change of the behavior of nn.utils.clip_grad_norm_ (it was working fine on PyTorch 0.4.0). We will fix this ASAP.

In the meantime, you can just remove ".item()" from that line and it should work.

**Comment by dariopavllo** [comment]
Fixed in 9d8485b. Thanks for flagging this!

**Comment by FrazierLei** [comment]
Thanks for your help!
